name: Deploy Deltas to Sandbox

# Definition when the workflow should run
on:
    workflow_dispatch:
        inputs:
            last-successful-commit-id:
                type: string
                required: true
                description: Id of Last Successfully Deployed Commit
    push:
        branches:
            - develop
            - work_on_deploy_script
env:
    SKIP_REMAINING_STAGES: false

# Jobs to be executed.
jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            # Install Salesforce CLI.
            -   name: 'Install Salesforce CLI'
                run: |
                    wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
                    mkdir ~/sfdx
                    tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
                    echo "$HOME/sfdx/bin" >> $GITHUB_PATH
                    ~/sfdx/bin/sfdx version

            # Install sfdx plugin
            -   name: 'Install plugin'
                shell: bash
                run: |
                    printf 'y\n' | sfdx plugins:install sfdx-git-delta@latest

            # Checkout the source code
            -   name: Checkout source code
                uses: actions/checkout@v3

            # prepare delta
            -   name: Prepare Delta
                shell: bash
                run: |
                    echo Last Commit to which the delta is prepared: ${{ github.sha }}
                    sfdx sgd:source:delta --to HEAD --from HEAD --output .
                    echo "LINES=$(wc -l < package/package.xml)" >> $GITHUB_ENV
                    less -FX package/package.xml

            # Deploy to target ORG
            -   name: Deploy to Target Org
                if: env.LINES != 3
                run: echo "${{ env.SKIP_REMAINING_STAGES }}"

            -   name: test if run
                if: env.LINES == 3
                run: echo "Name of the branch $GITHUB_REF_NAME"