name: Deploy Deltas to Sandbox

# Definition when the workflow should run
on:
    workflow_dispatch:
        inputs:
            last-successful-commit-id:
                type: string
                required: true
                description: Id of Last Successfully Deployed Commit
    push:
        branches:
            - develop
            - work_on_deploy_script

# Jobs to be executed.
jobs:
    getLastSuccessCommit:
        runs-on: ubuntu-latest
        name: Obtaining Last Successful Commit SHA
        outputs:
            output1: ${{ steps.step2.outputs.commit }}
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - uses: nrwl/last-successful-commit-action@v1
              id: step1
              with:
                  branch: ${{ github.ref_name }}
                  workflow_id: 'deltaDeploy.yml'
                  github_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Export value
              id: step2
              run: echo "::set-output name=commit::${{ steps.step1.outputs.commit_hash }}"

    deployment:
        runs-on: ubuntu-latest
        needs: getLastSuccessCommit
        steps:
            # Install Salesforce CLI.
            -   name: 'Install Salesforce CLI'
                run: |
                    wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
                    mkdir ~/sfdx
                    tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
                    echo "$HOME/sfdx/bin" >> $GITHUB_PATH
                    ~/sfdx/bin/sfdx version

            # Install sfdx plugin
            -   name: 'Install plugin'
                shell: bash
                run: |
                    printf 'y\n' | sfdx plugins:install sfdx-git-delta@latest

            # Checkout the source code
            -   name: Checkout source code
                uses: actions/checkout@v3

            # prepare delta
            -   name: Prepare Delta
                run: |
                    echo Last successful commit used: ${{needs.getLastSuccessCommit.outputs.output1}}                    
                    echo Last Commit to which the delta is prepared: ${{ github.sha }}
                    git show edba5ba20c67ee593c38e440725f23088f28b5a0
                    echo sfdx sgd:source:delta --to "HEAD" --from ${{ needs.getLastSuccessCommit.outputs.output1 }} --output .
                    sfdx sgd:source:delta --to "HEAD" --from ${{ needs.getLastSuccessCommit.outputs.output1 }} --output .
                    echo "LINES=$(wc -l < package/package.xml)" >> $GITHUB_ENV
                    cat package/package.xml

            # Obtain data stored in JSON to load all values
            -   name: Load JSON Settings
                uses: antifree/json-to-variables@v1.0.1
                with:
                    filename: '.github/settings/repositoryConfig.json'
                    prefix: settings

            # Deploy to QA
            -   name: Deploy to Target Org
                env:
                    JWT: ${{ secrets.QA_CERTIFICATE }}
                shell: bash
                if: env.LINES != 3 && github.ref_name == 'qa'
                run: |
                    echo "$JWT" | base64 --decode > ${HOME}/server.key
                    echo "running on branch ${GITHUB_REF_NAME}"
                    
                    sfdx force:auth:jwt:grant --clientid ${{ env.settings_develop_clientId }} -u ${{ env.settings_develop_username }} --jwtkeyfile ${HOME}/server.key --instanceurl ${{ env.settings_develop_instanceUrl }}
                    sfdx force:source:deploy -x package/package.xml -l RunLocalTests -u ${{ env.settings_develop_username }}
                    
                                  
            
